# Generated by Django 5.0.1 on 2024-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailing', '0003_dealer_date_created_dealer_debt_dealer_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
            preserve_default=False,
        ),
    ]
